import Link from "next/link";
import Image from "next/image";
import { Progress } from "@/components/ui/progress"; // Ensure you have this component
import { useActiveOrg } from "@/lib/hooks/useActiveOrg"; // Assuming this hook exists

// Define interface locally or import from your types file
export interface Course {
    slug: string;
    title: string;
    thumbnail?: string | null; 
    tutor?: string;
    progress?: number; // This comes from the backend annotation
}

const EnrolledCourseCard = ({ course }: { course: Course }) => {
    const { activeSlug } = useActiveOrg(); 

    const courseLearningHref = activeSlug
        ? `/${activeSlug}/course-learning/${course.slug}`
        : `/course-learning/${course.slug}`;

    const PRIMARY_BLUE = "text-[#3B9FC9]"; 
    
    // Ensure we have a valid number, fallback to 0
    const progressValue = Math.round(course.progress || 0);

    return (
        <Link href={courseLearningHref} className="block group h-full">
            <div className="bg-white p-1 overflow-hidden border border-gray-200 h-full flex flex-col rounded-md shadow-sm hover:shadow-md transition-all duration-200">
                
                {/* Thumbnail Section */}
                <div className="relative aspect-video bg-gray-100 w-full flex-shrink-0 overflow-hidden rounded-sm">
                    <Image
                        src={course.thumbnail || "/placeholder.svg"}
                        alt={course.title}
                        fill
                        sizes="(max-width: 640px) 100vw, (max-width: 768px) 50vw, 33vw"
                        style={{ objectFit: "cover" }}
                        className="group-hover:scale-105 transition-transform duration-300"
                    />
                </div>
                
                {/* Content Section */}
                <div className="p-3 flex flex-col flex-grow">
                    <h3 className={`font-bold text-base text-gray-800 mb-1 line-clamp-2 leading-tight group-hover:${PRIMARY_BLUE} transition-colors`}>
                        {course.title}
                    </h3>
                    
                    <p className="text-xs text-gray-500 mb-4 line-clamp-1">
                        {course.tutor || 'Instructor'}
                    </p>
                    
                    {/* Progress Section - Pushed to bottom */}
                    <div className="mt-auto pt-3 border-t border-gray-50">
                        <div className="flex justify-between items-end mb-1.5">
                            <span className="text-xs font-semibold text-gray-700">Progress</span>
                            <span className="text-xs font-bold text-blue-600">{progressValue}%</span>
                        </div>
                        
                        {/* Robust Styling: 
                           We use [&>div]:bg-blue-600 to target the inner indicator div 
                           generated by Radix UI/Shadcn without needing custom props.
                        */}
                        <Progress
                            value={progressValue}
                            className="h-2 w-full bg-gray-100 rounded-full [&>div]:bg-blue-600"
                        />
                    </div>
                </div>
            </div>
        </Link>
    );
};

export default EnrolledCourseCard;